name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Render Container Registry
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: echo $RENDER_API_KEY | docker login registry.render.com -u render --password-stdin

      - name: Build and Push Docker Image
        env:
          RENDER_SERVICE_NAME: student-performance
        run: |
          docker build -t registry.render.com/$RENDER_SERVICE_NAME:latest .
          docker push registry.render.com/$RENDER_SERVICE_NAME:latest

      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: your-render-service-id
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
               -H "Authorization: Bearer $RENDER_API_KEY" \
               -H "Accept: application/json" \
               -H "Content-Type: application/json" \
               --data '{"clearCache": false}'
